[package]
name = "order_management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
user_management = {path= "../user_management"}
rand = "0.5.5"